name: main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: python_setup
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: before_install
      run: |
        sudo apt-get install build-essential git libboost-all-dev cmake libgmp3-dev libssl-dev libsodium-dev libprocps-dev pkg-config gcc-5 g++-5
        sudo apt-get install clang-tidy
        git submodule init && git submodule update
        mkdir build
        cd build
        PATH=$PATH:${PWD}
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DUSE_CLANG_TIDY=ON ..
    - name: run_clang_tidy
      id: clang_tidy
      run: |
        cd build
        OUTPUT=$(python3 run-clang-tidy.py -quiet 2>&1)
        echo "::set-output name=OUTPUT::$OUTPUT"
        COUNT=$(echo $OUTPUT | grep "warning:" | wc -l)
        echo "::set-output name=COUNT::$COUNT"
    - name: check_errors
      if: steps.clang_tidy.outputs.COUNT > 0
      run: |
      exit 1
    - name: tests
      run: |
        cd build
        make
        make check

